### PR TITLE
Update notebooks with dask/numba optimizations

### PR DESCRIPTION
**Pull request by andersy005**
@wwieder, @jkshuman,

I was able to run the notebook, and made some progress at optimizing some parts. I'm still working on this, and will let you know when it's ready.

### CODE REVIEW

**Comment by wwieder** [comment]
thanks for your work on this and your help, Anderson.

**Comment by andersy005** [comment]
After tinkering with the source code from @jkshuman, my conclusion so far is that it is not possible to vectorize `calc_ffmc()`, `calc_dmc()`, `calc_dc()` functions due to the recursive formulation/data dependency (like the one below). Therefore, we are stuck with the **for loop** unless we can come up with a closed formulation (one that can be vectorized at CPU level without an explicit loop at the numpy level). 

```python
# create arrays to store output
FWIvars = ['ffmc','dmc','dc','isi','bui','fwi']
for v in range(len(FWIvars)):
    tempDS[FWIvars[v]]  = xr.DataArray(np.nan, coords=tempDS.tmax.coords)
    tempSSP[FWIvars[v]] = xr.DataArray(np.nan, coords=tempSSP.tmax.coords)

# loop over days to calculte FWI
for i in tqdm(range(len(tempDS.tmax))):
    # set initial values for
    if i == 0: 
        ffmc_prev, ffmc_ssp = 80, 80
        dmc_prev,  dmc_ssp  = 6,  6
        dc_prev,   dc_ssp   = 15, 15
    else: 
        ffmc_prev, ffmc_ssp = tempDS['ffmc'].data[i-1], tempSSP['ffmc'].data[i-1]
        dmc_prev,  dmc_ssp  = tempDS['dmc'].data[i-1],  tempSSP['dmc'].data[i-1]
        dc_prev,   dc_ssp   = tempDS['dc'].data[i-1],   tempSSP['dc'].data[i-1]

    # calc_ffmc(tempC, wind_kmhr, RH, precip_mm, ffmc_prev):
    tempDS.ffmc[i] = fwi.calc_ffmc(tempDS.tmax.data[i], tempDS.wind.data[i], 
                                   tempDS.RHREFHT.data[i], tempDS.PPT.data[i],ffmc_prev)
    tempSSP.ffmc[i] = fwi.calc_ffmc(tempSSP.tmax.data[i], tempSSP.wind.data[i], 
                                    tempSSP.RHREFHT.data[i], tempSSP.PPT.data[i],ffmc_ssp)
    # calc_dmc(tmaxC, RH, precip_mm, dmc_prev, month, latitude):
    tempDS.dmc[i] = fwi.calc_dmc(tempDS.tmax.data[i],  tempDS.RHREFHT.data[i],   
                                 tempDS.PPT.data[i], dmc_prev, 
                                 tempDS['time.month'][i], tempDS['lat'])
    tempSSP.dmc[i] = fwi.calc_dmc(tempSSP.tmax.data[i], tempSSP.RHREFHT.data[i], 
                                  tempSSP.PPT.data[i], dmc_ssp,
                                  tempDS['time.month'][i], tempDS['lat'])
    # calc_dc(tmaxC, precip_mm, dc_prev, month, latitude):
    tempDS.dc[i] = fwi.calc_dc(tempDS.tmax.data[i], tempDS.PPT.data[i], dc_prev, 
                                 tempDS['time.month'][i], tempDS['lat'])
    tempSSP.dc[i] = fwi.calc_dc(tempSSP.tmax.data[i], tempSSP.PPT.data[i], dc_ssp,
                                  tempDS['time.month'][i], tempDS['lat'])
```



@wwieder, the only part I was able to speed up is the `running_sum` computation. 

I hope this helps :). 


```python
def running_sum_np(data):
    v = pd.Series(data.copy())
    cumsum = v.cumsum().fillna(method='pad')
    reset = -cumsum[v.isnull()].diff().fillna(cumsum)
    result = v.where(v.notnull(), reset).cumsum()
    return result.values
```

Screen Shot 2021-02-24 at 11 36 55 PM

Screen Shot 2021-02-24 at 11 37 06 PM

Screen Shot 2021-02-24 at 11 43 06 PM

**Comment by wwieder** [comment]
Thanks for your help @andersy005

**Comment by andersy005** [comment]
Of course!

**Pull request merged**
